# FIXED
maincontrol_dsp.obj: ../maincontrol_dsp.c
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Device.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Adc.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_DevEmu.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_CpuTimers.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_ECan.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_ECap.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_DMA.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_EPwm.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_EQep.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Gpio.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_I2c.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_McBSP.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_PieCtrl.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_PieVect.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Spi.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Sci.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_SysCtrl.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_XIntrupt.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Xintf.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Examples.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_GlobalPrototypes.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_ePwm_defines.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Dma_defines.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_I2C_defines.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_DefaultISR.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/MotorCanCtrl.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/uart_fpga.h
maincontrol_dsp.obj: E:/CCS_workspace/maincontrol_dsp/include/algrithom.h
