# FIXED
MotorCanCtrl.obj: ../MotorCanCtrl.c
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Device.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Adc.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_DevEmu.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_CpuTimers.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_ECan.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_ECap.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_DMA.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_EPwm.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_EQep.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Gpio.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_I2c.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_McBSP.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_PieCtrl.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_PieVect.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Spi.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Sci.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_SysCtrl.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_XIntrupt.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Xintf.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Examples.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_GlobalPrototypes.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_ePwm_defines.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Dma_defines.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_I2C_defines.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_DefaultISR.h
MotorCanCtrl.obj: E:/CCS_workspace/maincontrol_dsp/include/MotorCanCtrl.h
