# FIXED
uart_fpga.obj: ../uart_fpga.c
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Device.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Adc.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_DevEmu.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_CpuTimers.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_ECan.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_ECap.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_DMA.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_EPwm.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_EQep.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Gpio.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_I2c.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_McBSP.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_PieCtrl.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_PieVect.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Spi.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Sci.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_SysCtrl.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_XIntrupt.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Xintf.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Examples.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_GlobalPrototypes.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_ePwm_defines.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Dma_defines.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_I2C_defines.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_DefaultISR.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/uart_fpga.h
uart_fpga.obj: E:/CCS_workspace/maincontrol_dsp/include/MotorCanCtrl.h
