# FIXED
algrithom.obj: ../algrithom.c
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Device.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Adc.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_DevEmu.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_CpuTimers.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_ECan.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_ECap.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_DMA.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_EPwm.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_EQep.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Gpio.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_I2c.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_McBSP.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_PieCtrl.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_PieVect.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Spi.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Sci.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_SysCtrl.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_XIntrupt.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Xintf.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Examples.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_GlobalPrototypes.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_ePwm_defines.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_Dma_defines.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_I2C_defines.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/DSP2833x_DefaultISR.h
algrithom.obj: E:/CCS_workspace/maincontrol_dsp/include/algrithom.h
